### ISSUE TITLE
[REPOSITORY] Update issue templates

### ISSUE THREAD

**Issue by jinseobhong** [jinseobhong/typescript.reactNative.template#16]
# Implementation <a href="#implementation" id="implementation">#</a>

This **issue** is about an issue **to be implement** in practice.

1. [What kind to implement](#what-kind-to-implement)
    - [Describe to What you are trying to solve by Implement](#describe-to-what-you-are-trying-to-solve-by-Implement)
    - [Implementation goals](#implementation-goals)
    - [Environment for implementation](#environment-for-implementation)
    - [Tasks of Implementation](#tasks-of-implementation)
    - [Describe alternatives](#describe-alternatives)
2. [Additional context](#additional-context)
3. [Reference](#reference)

##  What kind to implement <a href="#what-kind-of-implement" id="what-kind-of-implement">#</a>

Please check the type of implement. If it is not in the checklist, please check etc
- label list:
  - `Documentation`
  - `Environment`
  - `Feature`
  - `Fix`
  - `Re-factory`
  - `Repository`
  - `etc` 

### Describe to What you are trying to solve by Implement  <a href="#describe-to-what-you-are-trying-to-solve-by-implement" id="describe-to-what-you-are-trying-to-solve-by-implement">#</a>

It is necessary to reorganize the issue template to be more readable. Currently, issue templates are poorly readable, making it difficult to instantly recognize information.

### Implementation goals <a href="#implementation-goals" id="Implementation-goals">#</a>

- [x] Reorganized into recognizable issue templates in a procedural way 

### Environment for implementation ### Implementation goals <a href="#environment-for-implementation" id="environment-for-implementation">#</a>

Please write if there is an environment required for implementation 

- OS : [ e.g: Ubuntu 20.04 LTS, etc .. ]
- Java : [ e.g: openjdk 11.0.11 2021-04-20, etc .. ]
- Node : [ e.g: v16.3.0, etc .. ]
    - Package dependency manager :
        - npm : [ e.g: 7.15.1, etc .. ]
        - yarn : [ e.g: 1.22.10, etc .. ]
    - Packages :
        - dependencies :
            - something dependencies [ e.g: "react-native": "0.64.2", etc .. ]
            -
        - devDependencies :
            - something devDependencies [ e.g: "@babel/core": "^7.12.9", etc .. ]
            -

### Tasks of Implementation <a href="#tasks-of-implementation" id="tasks-of-implementation">#</a>

- [x] Update Bug report issue template
- [x] Update Implementation issue template
- [x] Update Question about something issue template
- [x] Update Suggest for this project issue template
- [x] Update Test for implementation issue template

### Describe alternatives <a href="#describe-alternatives" id="describe-alternatives">#</a>

If there is an alternative to this method, please let me know. if you have tried anything before to implement(in the order you tried), Steps to reproduce the behavior:

### Additional context <a href="#additional-context" id="additional-context">#</a>

Add any other context or screenshots about this issues
