### ISSUE TITLE
[TEST] Verify the native app build and run

### ISSUE THREAD

**Issue by jinseobhong** [jinseobhong/typescript.reactNative.template#3]
# Test for implementation <a href="#test-for-implementation" id="test-for-implementation">#</a>

To test the implementation

1. [What kind of implementation is the test for](#what-kind-of-implementation-is-the-test-for)
    - [Describe to What you are testing](#describe-to-what-you-are-testing)
    - [Test goals](#test-goals)
    - [Environment for test](#environment-for-test)
    - [Tasks of test](#tasks-of-test)
2. [Additional context](#additional-context)
3. [Reference](#reference)

## What kind of implementation is the test for <a href="#what-kind-of-implementation-is-the-test-for" id="what-kind-of-implementation-is-the-test-for">#</a>

Please check the type of **test** and add label, See [here](../blob/master/CONTRIBUTING.md#how-to-create-issue-about-test-for-implementation) to see what types are available.

### Describe to What you are testing <a href="#describe-to-what-you-are-testing" id="describe-to-what-you-are-testing">#</a>

Verify the native app build and run

### Test goals <a href="#test-goals" id="test-goals">#</a>

- [x] Test for android 
  - [x] Building native app
  - [x] Run native app
- [ ] Test for ios 
  - [ ] Building native app
  - [ ] Run native app

### Environment for test <a href="#environment-for-test" id="environment-for-test">#</a>

If you need to write an environment to test, Write down it.

#### Environment for Android
- OS : [ e.g: Ubuntu 20.04 LTS, etc .. ]
- Virtual execution environment
    - Java : [ e.g: openjdk 11.0.11 2021-04-20, etc .. ]
        - Android Studio :
        - Android SDK :
        - Android SDK Platform :
        - Android Virtual Device :
- Development tools
    - Node : v16.3.0
      - Package dependency manager : 
         - npm : 7.15.1
         - yarn : 1.22.10
      - Packages : 
        - dependencies : 
          - "react": "17.0.1"
          - "react-native": "0.64.2"
        - devDependencies :
          - "@babel/core": "^7.12.9",
          - "@babel/runtime": "^7.12.5",
          - "@react-native-community/eslint-config": "^2.0.0",
          - "babel-jest": "^26.6.3",
          - "eslint": "7.14.0",
          - "jest": "^26.6.3",
          - "metro-react-native-babel-preset": "^0.64.0",
          - "react-test-renderer": "17.0.1"

#### Environment for ios
- Mac OS :
- Virtual execution environment
    - Xcode :
    - CocoaPods :
- Development tools
    - Watchman :
    - Node : [ e.g: v16.3.0, etc .. ]
        - Package dependency manager :
            - npm : [ e.g: 7.15.1, etc .. ]
            - yarn :[ e.g: 1.22.10, etc .. ]
        - Packages :
            - dependencies :
                - something dependencies [ e.g: "react-native": "0.64.2", etc .. ]
                -
            - devDependencies :
                - something devDependencies [ e.g: "@babel/core": "^7.12.9", etc .. ]
                -

### Tasks of test <a href="#tasks-of-test" id="tasks-of-test">#</a>

- Building for android app
   1. Run command `npm install` in root directory(example: `home/jinseobhong/typescript.reactNative.template/`)
   2. Run command `npm start` or `react-native start` for running native app
   3. Run command `npm android` or `react-native run-android` for building native app 
- Building for ios app
   1.
 
## Additional context <a href="#additional-context" id="additional-context">#</a>

Once this test is complete, you should integrate typescript

## Reference <a href="#reference" id="reference">#</a>
