### ISSUE TITLE
[Repository] Creating Story Issue Template

### ISSUE THREAD

**Issue by jinseobhong** [jinseobhong/typescript.reactNative.template#34]
# Task <a href="#task" id="task">#</a>

This **issue** is about an issue **to be task** in practice.

1. [What kind to task](#what-kind-to-task)
    - [Describe to What you are trying to solve by Task](#describe-to-what-you-are-trying-to-solve-by-task)
    - [Task goals](#task-goals)
    - [Environment for task](#environment-for-task)
    - [Tasks of Task](#tasks-of-task)
    - [Describe alternatives](#describe-alternatives)
2. [Additional context](#additional-context)
3. [Reference](#reference)

##  What kind to task <a href="#what-kind-of-task" id="what-kind-of-task">#</a>

Please check the type of **task** and add label, See [here](../blob/master/CONTRIBUTING.md#how-to-create-issue-about-task) to see what types are available.

### Describe to What you are trying to solve by Task  <a href="#describe-to-what-you-are-trying-to-solve-by-task" id="describe-to-what-you-are-trying-to-solve-by-task">#</a>

Based on the 5W1H(who, what, where, when, why, how) principle, describes what the task will solve.
- 5W1H :
   - who : who do you solve problems for?
   - what : what is problem?
   - where: where is problem?
   - when: when did you have a problem?
   - how : How to solve the problem?
 
### Task goals <a href="#task-goals" id="Task-goals">#</a>

- [ ] Creating Stroy issue template

### Environment for task <a href="#environment-for-task" id="environment-for-task">#</a>

Please write if there is an environment required for task 

#### Environment for Android
- OS : [ e.g: Ubuntu 20.04 LTS, etc .. ]
- Virtual execution environment
    - Java : [ e.g: openjdk 11.0.11 2021-04-20, etc .. ]
        - Android Studio :
        - Android SDK :
        - Android SDK Platform :
        - Android Virtual Device :
- Development tools
    - Node : [ e.g: v16.3.0, etc .. ]
        - Package dependency manager :
            - npm : [ e.g: 7.15.1, etc .. ]
            - yarn :[ e.g: 1.22.10, etc .. ]
        - Packages :
            - dependencies :
                - something dependencies [ e.g: "react-native": "0.64.2", etc .. ]
                -
            - devDependencies :
                - something devDependencies [ e.g: "@babel/core": "^7.12.9", etc .. ]
                -

#### Environment for ios
- Mac OS :
- Virtual execution environment
    - Xcode :
    - CocoaPods :
- Development tools
    - Watchman :
    - Node : [ e.g: v16.3.0, etc .. ]
        - Package dependency manager :
            - npm : [ e.g: 7.15.1, etc .. ]
            - yarn :[ e.g: 1.22.10, etc .. ]
        - Packages :
            - dependencies :
                - something dependencies [ e.g: "react-native": "0.64.2", etc .. ]
                -
            - devDependencies :
                - something devDependencies [ e.g: "@babel/core": "^7.12.9", etc .. ]
                -

### Tasks of Task <a href="#tasks-of-task" id="tasks-of-task">#</a>

- [ ] Create Template Components
   - [ ] Description of the story
   - [ ] Story goals
   - [ ] Task of sub tasks
   - [ ] Reference
 
### Describe alternatives <a href="#describe-alternatives" id="describe-alternatives">#</a>

If there is an alternative to this method, please let me know. if you have tried anything before to task(in the order you tried), Steps to reproduce the behavior:

## Additional context <a href="#additional-context" id="additional-context">#</a>

Add any other context or screenshots about this issues
