### ISSUE TITLE
[Repository] Organize milestones into stories

### ISSUE THREAD

**Issue by jinseobhong** [jinseobhong/typescript.reactNative.template#38]
# Task <a href="#task" id="task">#</a>

This **issue** is about an issue **to be task** in practice.

1. [What kind to task](#what-kind-to-task)
    - [Describe to What you are trying to solve by Task](#describe-to-what-you-are-trying-to-solve-by-task)
    - [Task goals](#task-goals)
    - [Environment for task](#environment-for-task)
    - [Tasks of Task](#tasks-of-task)
    - [Describe alternatives](#describe-alternatives)
2. [Additional context](#additional-context)
3. [Reference](#reference)

##  What kind to task <a href="#what-kind-of-task" id="what-kind-of-task">#</a>

Please check the type of **task** and add label, See [here](../blob/master/CONTRIBUTING.md#how-to-create-issue-about-task) to see what types are available.

### Describe to What you are trying to solve by Task  <a href="#describe-to-what-you-are-trying-to-solve-by-task" id="describe-to-what-you-are-trying-to-solve-by-task">#</a>

Use stories closer to the agile development process to organize milestone goals

### Task goals <a href="#task-goals" id="Task-goals">#</a>

- [ ] Organize milestones into stories

### Environment for task <a href="#environment-for-task" id="environment-for-task">#</a>

Please write if there is an environment required for task 

#### Environment for Android
- OS : [ e.g: Ubuntu 20.04 LTS, etc .. ]
- Virtual execution environment
    - Java : [ e.g: openjdk 11.0.11 2021-04-20, etc .. ]
        - Android Studio :
        - Android SDK :
        - Android SDK Platform :
        - Android Virtual Device :
- Development tools
    - Node : [ e.g: v16.3.0, etc .. ]
        - Package dependency manager :
            - npm : [ e.g: 7.15.1, etc .. ]
            - yarn :[ e.g: 1.22.10, etc .. ]
        - Packages :
            - dependencies :
                - something dependencies [ e.g: "react-native": "0.64.2", etc .. ]
                -
            - devDependencies :
                - something devDependencies [ e.g: "@babel/core": "^7.12.9", etc .. ]
                -

#### Environment for ios
- Mac OS :
- Virtual execution environment
    - Xcode :
    - CocoaPods :
- Development tools
    - Watchman :
    - Node : [ e.g: v16.3.0, etc .. ]
        - Package dependency manager :
            - npm : [ e.g: 7.15.1, etc .. ]
            - yarn :[ e.g: 1.22.10, etc .. ]
        - Packages :Testing for non-functional task
            - dependencies :
                - something dependencies [ e.g: "react-native": "0.64.2", etc .. ]
                -
            - devDependencies :
                - something devDependencies [ e.g: "@babel/core": "^7.12.9", etc .. ]
                -

### Tasks <a href="#tasks-of-task" id="tasks-of-task">#</a>

- [x] Organize milestones into stories
   - [x] Creating documentation for the repository #42
   - [x] Fix functional error
   - [x] Fix non-functional error
   - [x] Set environment about development
   - [x] Set environment about repository
   - [x] Set workflow about repository
      - [x] [Documentation] Set issue templates #16 
   - [x] Task about functional
   - [x] Testing for functional task
   - [ ] Testing for non-functional task
   
### Describe alternatives <a href="#describe-alternatives" id="describe-alternatives">#</a>

If there is an alternative to this method, please let me know. if you have tried anything before to task(in the order you tried), Steps to reproduce the behavior:

## Additional context <a href="#additional-context" id="additional-context">#</a>

Add any other context or screenshots about this issues
