### ISSUE TITLE
[Documentation] Creating documentation for the repository

### ISSUE THREAD

**Issue by jinseobhong** [jinseobhong/typescript.reactNative.template#42]
# Story

- [Description of the story](#description-of-the-story)
- [Story goals](#test-goals)
- [Sub tasks](#sub-tasks)
- [Reference](#reference)

### Description of the story <a href="#description-of-the-story" id="description-of-the-story">#</a>

Creating documentation for the repository

### Story goals <a href="#story-goals" id="story-goals">#</a>

- [x] Creating documentation for the repository

### Sub tasks <a href="#sub-tasks" id="sub-tasks">#</a>

- [x] Create README.md for repository #19
- [x] Create CONTRIBUTING.md for repository #22
- [x] Create SECURITY.md for repository #43 
- [x]  Create CODE_OF_CONDUCT.md for repository #44

## Reference

When writing a story, write down what you referenced
