### ISSUE TITLE
[Test] Integration testing 

### ISSUE THREAD

**Issue by jinseobhong** [jinseobhong/typescript.reactNative.template#45]
# Story

- [Description of the story](#description-of-the-story)
- [Story goals](#test-goals)
- [Sub tasks](#sub-tasks)
- [Reference](#reference)

### Description of the story <a href="#description-of-the-story" id="description-of-the-story">#</a>

Please explain what kind of story you are collecting.

### Story goals <a href="#story-goals" id="story-goals">#</a>

- [x] Integration testing

### Sub tasks <a href="#sub-tasks" id="sub-tasks">#</a>

- [x] [TEST] Verify the native app build and run #3
- [x] [TEST] Integration Typescript module #6
- [x] [TEST] Check run test module via Jest #7

## Reference

When writing a story, write down what you referenced
